image: marthym/latex:1.0.0
variables:
  GIT_SUBMODULE_STRATEGY: recursive

songes-de-l-uhumele-SNAPSHOT:
  stage: build
  cache: 
    paths:
      - "SWR-Songes de l'Uhumele.pdf"
  script:
    - latexmk -f -r swr-class/latexmkrc || true
    - mv "build/songes-de-l-uhumele.pdf" "SWR-Songes de l'Uhumele.pdf"

  artifacts:
    expire_in: 1 day
    paths:
    - "SWR-Songes de l'Uhumele.pdf"
  allow_failure: true

songes-de-l-uhumele-RELEASE:
  stage: deploy
  script:
      - mv "SWR-Songes de l'Uhumele.pdf" "SWR-Songes de l'Uhumele v$CI_COMMIT_TAG.pdf"
  only:
    - tags
  artifacts:
    name: "SWR-Songes de l'Uhumele v$CI_COMMIT_TAG"
    paths:
    - "SWR-Songes de l'Uhumele.pdf"
  allow_failure: true